In [4]:
pip install requests

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests) (2025.4.26)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import requests

In [2]:
URL="https://stephen-king-api.onrender.com/api/books"
resp=requests.get(URL)

In [4]:
resp

In [14]:
json_data=resp.json()

In [15]:
json_data

{'data': [{'id': 1,
   'Year': 1974,
   'Title': 'Carrie',
   'handle': 'carrie',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-08695-0',
   'Pages': 199,
   'Notes': [''],
   'created_at': '2023-11-13T23:48:47.848Z',
   'villains': [{'name': 'Tina Blake',
     'url': 'https://stephen-king-api.onrender.com/api/villain/4'},
    {'name': 'Cindi',
     'url': 'https://stephen-king-api.onrender.com/api/villain/14'},
    {'name': 'Myra Crewes',
     'url': 'https://stephen-king-api.onrender.com/api/villain/16'},
    {'name': 'Billy deLois',
     'url': 'https://stephen-king-api.onrender.com/api/villain/25'},
    {'name': 'Kenny Garson',
     'url': 'https://stephen-king-api.onrender.com/api/villain/38'},
    {'name': 'Mary Lila Grace',
     'url': 'https://stephen-king-api.onrender.com/api/villain/44'},
    {'name': 'Christine Hargensen',
     'url': 'https://stephen-king-api.onrender.com/api/villain/49'},
    {'name': 'Vic Mooney',
     'url': 'https://stephen-king-api.onrender.com/api/villain/75'},
    {'name': 'The Mortimer Snerds',
     'url': 'https://stephen-king-api.onrender.com/api/villain/77'},
    {'name': 'Billy Nolan',
     'url': 'https://stephen-king-api.onrender.com/api/villain/80'},
    {'name': 'Elenor Richmond',
     'url': 'https://stephen-king-api.onrender.com/api/villain/90'},
    {'name': 'Rachel Spies',
     'url': 'https://stephen-king-api.onrender.com/api/villain/94'},
    {'name': 'Jackie Talbot',
     'url': 'https://stephen-king-api.onrender.com/api/villain/99'},
    {'name': 'Donna and Mary Lila Grace Thibodeau',
     'url': 'https://stephen-king-api.onrender.com/api/villain/102'},
    {'name': 'Jessica Upshaw',
     'url': 'https://stephen-king-api.onrender.com/api/villain/108'},
    {'name': 'Norma Watson',
     'url': 'https://stephen-king-api.onrender.com/api/villain/109'},
    {'name': 'Margaret White',
     'url': 'https://stephen-king-api.onrender.com/api/villain/113'}]},
  {'id': 2,
   'Year': 1975,
   'Title': "Salem's Lot",
   'handle': 'salem-s-lot',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-00751-1',
   'Pages': 439,
   'Notes': ['Nominee, World Fantasy Award, 1976[2]'],
   'created_at': '2023-11-13T23:48:48.098Z',
   'villains': [{'name': 'Kurt Barlow',
     'url': 'https://stephen-king-api.onrender.com/api/villain/2'},
    {'name': 'Richard Straker',
     'url': 'https://stephen-king-api.onrender.com/api/villain/98'}]},
  {'id': 3,
   'Year': 1977,
   'Title': 'The Shining',
   'handle': 'the-shining',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-12167-5',
   'Pages': 447,
   'Notes': ['Runner-up (4th place), Locus Award for Best Fantasy Novel, 1978[2]'],
   'created_at': '2023-11-13T23:48:48.219Z',
   'villains': [{'name': 'Horace M. Derwent',
     'url': 'https://stephen-king-api.onrender.com/api/villain/26'},
    {'name': 'Delbert Grady',
     'url': 'https://stephen-king-api.onrender.com/api/villain/45'},
    {'name': 'Jack Torrance',
     'url': 'https://stephen-king-api.onrender.com/api/villain/106'}]},
  {'id': 4,
   'Year': 1977,
   'Title': 'Rage',
   'handle': 'rage',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-07645-8',
   'Pages': 211,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:48.339Z',
   'villains': []},
  {'id': 5,
   'Year': 1978,
   'Title': 'The Stand',
   'handle': 'the-stand',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-12168-2',
   'Pages': 823,
   'Notes': ['Nominee, World Fantasy Award, 1979',
    'Runner-up (15th place), Locus Award, 1979[2]'],
   'created_at': '2023-11-13T23:48:48.477Z',
   'villains': [{'name': 'Donald Merwin Elbert',
     'url': 'https://stephen-king-api.onrender.com/api/villain/34'},
    {'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'},
    {'name': 'Lloyd Henreid',
     'url': 'https://stephen-king-api.onrender.com/api/villain/51'},
    {'name': 'The Kid',
     'url': 'https://stephen-king-api.onrender.com/api/villain/62'},
    {'name': 'Harold Lauder',
     'url': 'https://stephen-king-api.onrender.com/api/villain/64'},
    {'name': 'Rat Man',
     'url': 'https://stephen-king-api.onrender.com/api/villain/87'}]},
  {'id': 6,
   'Year': 1979,
   'Title': 'The Long Walk',
   'handle': 'the-long-walk',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-08754-6',
   'Pages': 384,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:48.608Z',
   'villains': [{'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'},
    {'name': 'The Major',
     'url': 'https://stephen-king-api.onrender.com/api/villain/70'}]},
  {'id': 7,
   'Year': 1979,
   'Title': 'The Dead Zone',
   'handle': 'the-dead-zone',
   'Publisher': 'Viking Press',
   'ISBN': '978-0-670-26077-5',
   'Pages': 428,
   'Notes': ['Runner-up (2nd place), Locus Award for Best Fantasy Novel, 1980[2]'],
   'created_at': '2023-11-13T23:48:48.753Z',
   'villains': [{'name': 'Frank Dodd',
     'url': 'https://stephen-king-api.onrender.com/api/villain/29'},
    {'name': 'Henrietta Dodd',
     'url': 'https://stephen-king-api.onrender.com/api/villain/30'},
    {'name': 'Malcolm Janus',
     'url': 'https://stephen-king-api.onrender.com/api/villain/71'},
    {'name': 'Sonny Elliman',
     'url': 'https://stephen-king-api.onrender.com/api/villain/93'},
    {'name': 'Greg Stillson',
     'url': 'https://stephen-king-api.onrender.com/api/villain/97'},
    {'name': "The Devil's Dozen",
     'url': 'https://stephen-king-api.onrender.com/api/villain/100'}]},
  {'id': 8,
   'Year': 1980,
   'Title': 'Firestarter',
   'handle': 'firestarter',
   'Publisher': 'Viking Press',
   'ISBN': '978-0-670-31541-3',
   'Pages': 426,
   'Notes': ['Nominee, British Fantasy Award’s August Derleth Award, 1981',
    'Runner-up (8th place), Locus Award for Best Science Fiction Novel, 1981[2]'],
   'created_at': '2023-11-13T23:48:48.876Z',
   'villains': [{'name': 'James Hollister',
     'url': 'https://stephen-king-api.onrender.com/api/villain/54'},
    {'name': 'Charlie McGee',
     'url': 'https://stephen-king-api.onrender.com/api/villain/73'},
    {'name': 'John Rainbird',
     'url': 'https://stephen-king-api.onrender.com/api/villain/86'}]},
  {'id': 9,
   'Year': 1981,
   'Title': 'Roadwork',
   'handle': 'roadwork',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-09668-5',
   'Pages': 274,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:49.005Z',
   'villains': []},
  {'id': 10,
   'Year': 1981,
   'Title': 'Cujo',
   'handle': 'cujo',
   'Publisher': 'Viking Press',
   'ISBN': '978-0-670-45193-7',
   'Pages': 319,
   'Notes': ['Winner, British Fantasy Award’s August Derleth Award, 1982',
    'Runner-up (21st place), Locus Award for Best Fantasy Novel, 1982[2]'],
   'created_at': '2023-11-13T23:48:49.131Z',
   'villains': [{'name': 'Cujo',
     'url': 'https://stephen-king-api.onrender.com/api/villain/19'}]},
  {'id': 11,
   'Year': 1982,
   'Title': 'The Running Man',
   'handle': 'the-running-man',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-11508-9',
   'Pages': 219,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:49.252Z',
   'villains': [{'name': 'The Gladiators',
     'url': 'https://stephen-king-api.onrender.com/api/villain/42'},
    {'name': 'Damon Killian',
     'url': 'https://stephen-king-api.onrender.com/api/villain/63'}]},
  {'id': 12,
   'Year': 1982,
   'Title': 'The Dark Tower: The Gunslinger',
   'handle': 'the-dark-tower-the-gunslinger',
   'Publisher': 'Grant',
   'ISBN': '978-0-937986-50-9',
   'Pages': 224,
   'Notes': [''],
   'created_at': '2023-11-13T23:48:49.374Z',
   'villains': [{'name': 'Marten Broadcloak',
     'url': 'https://stephen-king-api.onrender.com/api/villain/10'},
    {'name': 'Crimson King',
     'url': 'https://stephen-king-api.onrender.com/api/villain/17'},
    {'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'},
    {'name': 'Sylvia Pittston',
     'url': 'https://stephen-king-api.onrender.com/api/villain/84'}]},
  {'id': 13,
   'Year': 1983,
   'Title': 'Christine',
   'handle': 'christine',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-22026-7',
   'Pages': 526,
   'Notes': ['Runner-up (6th place), Locus Award for Best Fantasy Novel, 1984[2]'],
   'created_at': '2023-11-13T23:48:49.505Z',
   'villains': [{'name': 'Christine (car)',
     'url': 'https://stephen-king-api.onrender.com/api/villain/11'},
    {'name': 'Arnie Cunningham',
     'url': 'https://stephen-king-api.onrender.com/api/villain/20'}]},
  {'id': 14,
   'Year': 1983,
   'Title': 'Pet Sematary',
   'handle': 'pet-sematary',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-18244-7',
   'Pages': 374,
   'Notes': ['Nominee, World Fantasy Award, 1984',
    'Runner-up (7th place), Locus Award for Best Fantasy Novel, 1984[2]'],
   'created_at': '2023-11-13T23:48:49.637Z',
   'villains': [{'name': 'Winston Church',
     'url': 'https://stephen-king-api.onrender.com/api/villain/13'},
    {'name': 'Gage Creed',
     'url': 'https://stephen-king-api.onrender.com/api/villain/15'},
    {'name': 'Victor Pascow',
     'url': 'https://stephen-king-api.onrender.com/api/villain/83'},
    {'name': 'Wendigo',
     'url': 'https://stephen-king-api.onrender.com/api/villain/110'}]},
  {'id': 15,
   'Year': 1983,
   'Title': 'Cycle of the Werewolf',
   'handle': 'cycle-of-the-werewolf',
   'Publisher': 'Land of Enchantment',
   'ISBN': '978-0-960-38282-8',
   'Pages': 127,
   'Notes': ['Illustrated by Bernie Wrightson'],
   'created_at': '2023-11-13T23:48:49.757Z',
   'villains': [{'name': 'Lester Lowe',
     'url': 'https://stephen-king-api.onrender.com/api/villain/68'}]},
  {'id': 16,
   'Year': 1984,
   'Title': 'The Talisman',
   'handle': 'the-talisman',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-69199-9',
   'Pages': 646,
   'Notes': ['Written with Peter Straub',
    'Nominee, World Fantasy Award, 1985',
    'Runner-up (4th place), Locus Award for Best Fantasy Novel, 1985[2]'],
   'created_at': '2023-11-13T23:48:49.872Z',
   'villains': []},
  {'id': 17,
   'Year': 1984,
   'Title': 'The Eyes of the Dragon',
   'handle': 'the-eyes-of-the-dragon',
   'Publisher': 'Philtrum Press (1984)Viking (1987)',
   'ISBN': '978-0-670-81458-9',
   'Pages': 326,
   'Notes': ['First published as a limited edition in 1984, then for the mass market in 1987'],
   'created_at': '2023-11-13T23:48:49.988Z',
   'villains': [{'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'}]},
  {'id': 18,
   'Year': 1984,
   'Title': 'Thinner',
   'handle': 'thinner',
   'Publisher': 'NAL',
   'ISBN': '978-0-453-00468-8',
   'Pages': 309,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:50.102Z',
   'villains': []},
  {'id': 19,
   'Year': 1986,
   'Title': 'It',
   'handle': 'it',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-81302-5',
   'Pages': 1138,
   'Notes': ['Winner, British Fantasy Award’s August Derleth Award, 1987',
    'Nominee, World Fantasy Award, 1987',
    'Runner-up (3rd place), Locus Award for Best Fantasy Novel, 1987[2]'],
   'created_at': '2023-11-13T23:48:50.223Z',
   'villains': [{'name': 'Henry Bowers',
     'url': 'https://stephen-king-api.onrender.com/api/villain/7'},
    {'name': 'Butch Bowers',
     'url': 'https://stephen-king-api.onrender.com/api/villain/8'},
    {'name': 'Greta Bowie',
     'url': 'https://stephen-king-api.onrender.com/api/villain/9'},
    {'name': 'Victor Criss',
     'url': 'https://stephen-king-api.onrender.com/api/villain/18'},
    {'name': 'Marcia Fadden',
     'url': 'https://stephen-king-api.onrender.com/api/villain/35'},
    {'name': 'John Garton',
     'url': 'https://stephen-king-api.onrender.com/api/villain/39'},
    {'name': 'Peter Gordon',
     'url': 'https://stephen-king-api.onrender.com/api/villain/43'},
    {'name': 'Patrick Hockstetter',
     'url': 'https://stephen-king-api.onrender.com/api/villain/53'},
    {'name': 'Belch Huggins',
     'url': 'https://stephen-king-api.onrender.com/api/villain/55'},
    {'name': 'It (Creature)',
     'url': 'https://stephen-king-api.onrender.com/api/villain/57'},
    {'name': 'Richard P. Macklin',
     'url': 'https://stephen-king-api.onrender.com/api/villain/69'},
    {'name': 'Alvin Marsh',
     'url': 'https://stephen-king-api.onrender.com/api/villain/72'},
    {'name': 'Sally Mueller',
     'url': 'https://stephen-king-api.onrender.com/api/villain/79'},
    {'name': 'Tom Rogan',
     'url': 'https://stephen-king-api.onrender.com/api/villain/91'},
    {'name': 'Christopher Unwin',
     'url': 'https://stephen-king-api.onrender.com/api/villain/107'}]},
  {'id': 20,
   'Year': 1987,
   'Title': 'The Dark Tower II: The Drawing of the Three',
   'handle': 'the-dark-tower-ii-the-drawing-of-the-three',
   'Publisher': 'Grant',
   'ISBN': '978-0-937986-90-5',
   'Pages': 400,
   'Notes': ['Runner-up (16th place), Locus Award for Best Fantasy Novel, 1988[2]'],
   'created_at': '2023-11-13T23:48:50.339Z',
   'villains': [{'name': 'Jack Mort',
     'url': 'https://stephen-king-api.onrender.com/api/villain/76'}]},
  {'id': 21,
   'Year': 1987,
   'Title': 'Misery',
   'handle': 'misery',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-81364-3',
   'Pages': 310,
   'Notes': ['Winner, Bram Stoker Award, 1988',
    'Nominee, World Fantasy Award, 1988[2]'],
   'created_at': '2023-11-13T23:48:50.459Z',
   'villains': [{'name': 'Annie Wilkes',
     'url': 'https://stephen-king-api.onrender.com/api/villain/114'}]},
  {'id': 22,
   'Year': 1987,
   'Title': 'The Tommyknockers',
   'handle': 'the-tommyknockers',
   'Publisher': 'Putnam',
   'ISBN': '978-0-399-13314-5',
   'Pages': 558,
   'Notes': ['Runner-up (16th place), Locus Award for Best Science Fiction Novel, 1988[2]'],
   'created_at': '2023-11-13T23:48:50.579Z',
   'villains': [{'name': 'Tommyknockers',
     'url': 'https://stephen-king-api.onrender.com/api/villain/104'}]},
  {'id': 23,
   'Year': 1989,
   'Title': 'The Dark Half',
   'handle': 'the-dark-half',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-82982-8',
   'Pages': 431,
   'Notes': ['Runner-up (2nd place), Locus Award for Best Horror Novel, 1990[2]'],
   'created_at': '2023-11-13T23:48:50.696Z',
   'villains': [{'name': 'George Stark',
     'url': 'https://stephen-king-api.onrender.com/api/villain/96'}]},
  {'id': 24,
   'Year': 1990,
   'Title': 'The Stand Uncut',
   'handle': 'the-stand-uncut',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-19957-5',
   'Pages': 1152,
   'Notes': ['The Complete & Uncut Edition',
    "Runner-up (2nd place), Locus Award's Best Horror/Dark Fantasy Novel, 1991[2]"],
   'created_at': '2023-11-13T23:48:50.809Z',
   'villains': []},
  {'id': 25,
   'Year': 1991,
   'Title': 'The Dark Tower III: The Waste Lands',
   'handle': 'the-dark-tower-iii-the-waste-lands',
   'Publisher': 'Grant',
   'ISBN': '978-0-937986-17-2',
   'Pages': 512,
   'Notes': ['Nominee, Bram Stoker Award, 1992',
    'Runner-up (3rd place), Locus Award for Best Horror/Dark Fantasy Novel, 1992[2]'],
   'created_at': '2023-11-13T23:48:50.926Z',
   'villains': [{'name': 'Blaine the Mono',
     'url': 'https://stephen-king-api.onrender.com/api/villain/3'},
    {'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'}]},
  {'id': 26,
   'Year': 1991,
   'Title': 'Needful Things',
   'handle': 'needful-things',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-83953-7',
   'Pages': 690,
   'Notes': ['Nominee, Bram Stoker Award, 1992',
    'Runner-up (13th place), Locus Award for Best Horror/Dark Fantasy Novel, 1992[2]'],
   'created_at': '2023-11-13T23:48:51.044Z',
   'villains': [{'name': 'Leland Gaunt',
     'url': 'https://stephen-king-api.onrender.com/api/villain/40'}]},
  {'id': 27,
   'Year': 1992,
   'Title': "Gerald's Game",
   'handle': 'gerald-s-game',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-84650-4',
   'Pages': 352,
   'Notes': [],
   'created_at': '2023-11-13T23:48:51.165Z',
   'villains': [{'name': 'Gerald Burlingame',
     'url': 'https://stephen-king-api.onrender.com/api/villain/41'},
    {'name': 'Raymond Andrew Joubert',
     'url': 'https://stephen-king-api.onrender.com/api/villain/61'},
    {'name': 'Tom Mahout',
     'url': 'https://stephen-king-api.onrender.com/api/villain/103'}]},
  {'id': 28,
   'Year': 1992,
   'Title': 'Dolores Claiborne',
   'handle': 'dolores-claiborne',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-84452-4',
   'Pages': 305,
   'Notes': ['Runner-up (14th place), Locus Award for Best Horror/Dark Fantasy Novel, 1993[2]'],
   'created_at': '2023-11-13T23:48:51.295Z',
   'villains': [{'name': 'Joe St. George',
     'url': 'https://stephen-king-api.onrender.com/api/villain/95'}]},
  {'id': 29,
   'Year': 1994,
   'Title': 'Insomnia',
   'handle': 'insomnia',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-85503-2',
   'Pages': 787,
   'Notes': ['Nominee, Bram Stoker Award, 1995',
    'Runner-up (3rd place), Locus Award for Best Fantasy/Horror Novel, 1995[2]'],
   'created_at': '2023-11-13T23:48:51.415Z',
   'villains': [{'name': 'Crimson King',
     'url': 'https://stephen-king-api.onrender.com/api/villain/17'},
    {'name': 'Susan Day',
     'url': 'https://stephen-king-api.onrender.com/api/villain/23'}]},
  {'id': 30,
   'Year': 1995,
   'Title': 'Rose Madder',
   'handle': 'rose-madder',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-85869-9',
   'Pages': 420,
   'Notes': ['Runner-up (3rd place), Locus Award for Best Horror/Dark Fantasy Novel, 1995[2]'],
   'created_at': '2023-11-13T23:48:51.533Z',
   'villains': [{'name': 'Norman Daniels',
     'url': 'https://stephen-king-api.onrender.com/api/villain/22'},
    {'name': 'Susan Day',
     'url': 'https://stephen-king-api.onrender.com/api/villain/23'}]},
  {'id': 31,
   'Year': 1996,
   'Title': 'The Green Mile',
   'handle': 'the-green-mile',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-19049-9978-0-451-19052-9978-0-451-19054-3978-0-451-19055-0978-0-451-19056-7978-0-451-19057-4',
   'Pages': 400,
   'Notes': ['Winner, Bram Stoker Award, 1997',
    'Runner-up (8th place), Locus Award for Best Horror/Dark Fantasy Novel, 1997[2]'],
   'created_at': '2023-11-13T23:48:51.660Z',
   'villains': [{'name': 'Percy Wetmore',
     'url': 'https://stephen-king-api.onrender.com/api/villain/111'},
    {'name': 'William Wharton',
     'url': 'https://stephen-king-api.onrender.com/api/villain/112'}]},
  {'id': 32,
   'Year': 1996,
   'Title': 'Desperation',
   'handle': 'desperation',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-86836-0',
   'Pages': 704,
   'Notes': ['Twin novel of The Regulators',
    'Winner, Locus Award for Best Horror/Dark Fantasy Novel, 1997[2]'],
   'created_at': '2023-11-13T23:48:51.784Z',
   'villains': []},
  {'id': 33,
   'Year': 1996,
   'Title': 'The Regulators',
   'handle': 'the-regulators',
   'Publisher': 'Dutton',
   'ISBN': '978-0-525-94190-3',
   'Pages': 480,
   'Notes': ['Published under pseudonym Richard Bachman',
    'Twin novel of Desperation'],
   'created_at': '2023-11-13T23:48:51.900Z',
   'villains': []},
  {'id': 34,
   'Year': 1997,
   'Title': 'The Dark Tower IV: Wizard and Glass',
   'handle': 'the-dark-tower-iv-wizard-and-glass',
   'Publisher': 'Grant',
   'ISBN': '978-1-880418-38-3',
   'Pages': 787,
   'Notes': ['Runner-up (4th place), Locus Award for Best Fantasy Novel, 1998',
    'Runner-up (6th place), Locus Award for Best Art Book, 1998[2]'],
   'created_at': '2023-11-13T23:48:52.019Z',
   'villains': [{'name': 'Blaine the Mono',
     'url': 'https://stephen-king-api.onrender.com/api/villain/3'},
    {'name': 'Cordelia Delgado',
     'url': 'https://stephen-king-api.onrender.com/api/villain/24'},
    {'name': 'Rhea Dubativo',
     'url': 'https://stephen-king-api.onrender.com/api/villain/32'},

In [20]:
import pandas as pd

df=pd.json_normalize(json_data["data"])
df=df[["id","Title","Year","ISBN"]]

In [21]:
df

    id          Title  Year               ISBN
0    1         Carrie  1974  978-0-385-08695-0
1    2    Salem's Lot  1975  978-0-385-00751-1
2    3    The Shining  1977  978-0-385-12167-5
3    4           Rage  1977  978-0-451-07645-8
4    5      The Stand  1978  978-0-385-12168-2
..  ..            ...   ...                ...
58  59   The Outsider  2018  978-1-50118-098-9
59  60      Elevation  2018  978-1-98210-231-9
60  61  The Institute  2019  978-1-98211-056-7
61  62          Later  2021  978-1-78909-649-1
62  63  Billy Summers  2021  978-1-982-17361-6

[63 rows x 4 columns]

In [26]:
json_data

{'data': [{'id': 1,
   'Year': 1974,
   'Title': 'Carrie',
   'handle': 'carrie',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-08695-0',
   'Pages': 199,
   'Notes': [''],
   'created_at': '2023-11-13T23:48:47.848Z',
   'villains': [{'name': 'Tina Blake',
     'url': 'https://stephen-king-api.onrender.com/api/villain/4'},
    {'name': 'Cindi',
     'url': 'https://stephen-king-api.onrender.com/api/villain/14'},
    {'name': 'Myra Crewes',
     'url': 'https://stephen-king-api.onrender.com/api/villain/16'},
    {'name': 'Billy deLois',
     'url': 'https://stephen-king-api.onrender.com/api/villain/25'},
    {'name': 'Kenny Garson',
     'url': 'https://stephen-king-api.onrender.com/api/villain/38'},
    {'name': 'Mary Lila Grace',
     'url': 'https://stephen-king-api.onrender.com/api/villain/44'},
    {'name': 'Christine Hargensen',
     'url': 'https://stephen-king-api.onrender.com/api/villain/49'},
    {'name': 'Vic Mooney',
     'url': 'https://stephen-king-api.onrender.com/api/villain/75'},
    {'name': 'The Mortimer Snerds',
     'url': 'https://stephen-king-api.onrender.com/api/villain/77'},
    {'name': 'Billy Nolan',
     'url': 'https://stephen-king-api.onrender.com/api/villain/80'},
    {'name': 'Elenor Richmond',
     'url': 'https://stephen-king-api.onrender.com/api/villain/90'},
    {'name': 'Rachel Spies',
     'url': 'https://stephen-king-api.onrender.com/api/villain/94'},
    {'name': 'Jackie Talbot',
     'url': 'https://stephen-king-api.onrender.com/api/villain/99'},
    {'name': 'Donna and Mary Lila Grace Thibodeau',
     'url': 'https://stephen-king-api.onrender.com/api/villain/102'},
    {'name': 'Jessica Upshaw',
     'url': 'https://stephen-king-api.onrender.com/api/villain/108'},
    {'name': 'Norma Watson',
     'url': 'https://stephen-king-api.onrender.com/api/villain/109'},
    {'name': 'Margaret White',
     'url': 'https://stephen-king-api.onrender.com/api/villain/113'}]},
  {'id': 2,
   'Year': 1975,
   'Title': "Salem's Lot",
   'handle': 'salem-s-lot',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-00751-1',
   'Pages': 439,
   'Notes': ['Nominee, World Fantasy Award, 1976[2]'],
   'created_at': '2023-11-13T23:48:48.098Z',
   'villains': [{'name': 'Kurt Barlow',
     'url': 'https://stephen-king-api.onrender.com/api/villain/2'},
    {'name': 'Richard Straker',
     'url': 'https://stephen-king-api.onrender.com/api/villain/98'}]},
  {'id': 3,
   'Year': 1977,
   'Title': 'The Shining',
   'handle': 'the-shining',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-12167-5',
   'Pages': 447,
   'Notes': ['Runner-up (4th place), Locus Award for Best Fantasy Novel, 1978[2]'],
   'created_at': '2023-11-13T23:48:48.219Z',
   'villains': [{'name': 'Horace M. Derwent',
     'url': 'https://stephen-king-api.onrender.com/api/villain/26'},
    {'name': 'Delbert Grady',
     'url': 'https://stephen-king-api.onrender.com/api/villain/45'},
    {'name': 'Jack Torrance',
     'url': 'https://stephen-king-api.onrender.com/api/villain/106'}]},
  {'id': 4,
   'Year': 1977,
   'Title': 'Rage',
   'handle': 'rage',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-07645-8',
   'Pages': 211,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:48.339Z',
   'villains': []},
  {'id': 5,
   'Year': 1978,
   'Title': 'The Stand',
   'handle': 'the-stand',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-12168-2',
   'Pages': 823,
   'Notes': ['Nominee, World Fantasy Award, 1979',
    'Runner-up (15th place), Locus Award, 1979[2]'],
   'created_at': '2023-11-13T23:48:48.477Z',
   'villains': [{'name': 'Donald Merwin Elbert',
     'url': 'https://stephen-king-api.onrender.com/api/villain/34'},
    {'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'},
    {'name': 'Lloyd Henreid',
     'url': 'https://stephen-king-api.onrender.com/api/villain/51'},
    {'name': 'The Kid',
     'url': 'https://stephen-king-api.onrender.com/api/villain/62'},
    {'name': 'Harold Lauder',
     'url': 'https://stephen-king-api.onrender.com/api/villain/64'},
    {'name': 'Rat Man',
     'url': 'https://stephen-king-api.onrender.com/api/villain/87'}]},
  {'id': 6,
   'Year': 1979,
   'Title': 'The Long Walk',
   'handle': 'the-long-walk',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-08754-6',
   'Pages': 384,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:48.608Z',
   'villains': [{'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'},
    {'name': 'The Major',
     'url': 'https://stephen-king-api.onrender.com/api/villain/70'}]},
  {'id': 7,
   'Year': 1979,
   'Title': 'The Dead Zone',
   'handle': 'the-dead-zone',
   'Publisher': 'Viking Press',
   'ISBN': '978-0-670-26077-5',
   'Pages': 428,
   'Notes': ['Runner-up (2nd place), Locus Award for Best Fantasy Novel, 1980[2]'],
   'created_at': '2023-11-13T23:48:48.753Z',
   'villains': [{'name': 'Frank Dodd',
     'url': 'https://stephen-king-api.onrender.com/api/villain/29'},
    {'name': 'Henrietta Dodd',
     'url': 'https://stephen-king-api.onrender.com/api/villain/30'},
    {'name': 'Malcolm Janus',
     'url': 'https://stephen-king-api.onrender.com/api/villain/71'},
    {'name': 'Sonny Elliman',
     'url': 'https://stephen-king-api.onrender.com/api/villain/93'},
    {'name': 'Greg Stillson',
     'url': 'https://stephen-king-api.onrender.com/api/villain/97'},
    {'name': "The Devil's Dozen",
     'url': 'https://stephen-king-api.onrender.com/api/villain/100'}]},
  {'id': 8,
   'Year': 1980,
   'Title': 'Firestarter',
   'handle': 'firestarter',
   'Publisher': 'Viking Press',
   'ISBN': '978-0-670-31541-3',
   'Pages': 426,
   'Notes': ['Nominee, British Fantasy Award’s August Derleth Award, 1981',
    'Runner-up (8th place), Locus Award for Best Science Fiction Novel, 1981[2]'],
   'created_at': '2023-11-13T23:48:48.876Z',
   'villains': [{'name': 'James Hollister',
     'url': 'https://stephen-king-api.onrender.com/api/villain/54'},
    {'name': 'Charlie McGee',
     'url': 'https://stephen-king-api.onrender.com/api/villain/73'},
    {'name': 'John Rainbird',
     'url': 'https://stephen-king-api.onrender.com/api/villain/86'}]},
  {'id': 9,
   'Year': 1981,
   'Title': 'Roadwork',
   'handle': 'roadwork',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-09668-5',
   'Pages': 274,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:49.005Z',
   'villains': []},
  {'id': 10,
   'Year': 1981,
   'Title': 'Cujo',
   'handle': 'cujo',
   'Publisher': 'Viking Press',
   'ISBN': '978-0-670-45193-7',
   'Pages': 319,
   'Notes': ['Winner, British Fantasy Award’s August Derleth Award, 1982',
    'Runner-up (21st place), Locus Award for Best Fantasy Novel, 1982[2]'],
   'created_at': '2023-11-13T23:48:49.131Z',
   'villains': [{'name': 'Cujo',
     'url': 'https://stephen-king-api.onrender.com/api/villain/19'}]},
  {'id': 11,
   'Year': 1982,
   'Title': 'The Running Man',
   'handle': 'the-running-man',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-11508-9',
   'Pages': 219,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:49.252Z',
   'villains': [{'name': 'The Gladiators',
     'url': 'https://stephen-king-api.onrender.com/api/villain/42'},
    {'name': 'Damon Killian',
     'url': 'https://stephen-king-api.onrender.com/api/villain/63'}]},
  {'id': 12,
   'Year': 1982,
   'Title': 'The Dark Tower: The Gunslinger',
   'handle': 'the-dark-tower-the-gunslinger',
   'Publisher': 'Grant',
   'ISBN': '978-0-937986-50-9',
   'Pages': 224,
   'Notes': [''],
   'created_at': '2023-11-13T23:48:49.374Z',
   'villains': [{'name': 'Marten Broadcloak',
     'url': 'https://stephen-king-api.onrender.com/api/villain/10'},
    {'name': 'Crimson King',
     'url': 'https://stephen-king-api.onrender.com/api/villain/17'},
    {'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'},
    {'name': 'Sylvia Pittston',
     'url': 'https://stephen-king-api.onrender.com/api/villain/84'}]},
  {'id': 13,
   'Year': 1983,
   'Title': 'Christine',
   'handle': 'christine',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-22026-7',
   'Pages': 526,
   'Notes': ['Runner-up (6th place), Locus Award for Best Fantasy Novel, 1984[2]'],
   'created_at': '2023-11-13T23:48:49.505Z',
   'villains': [{'name': 'Christine (car)',
     'url': 'https://stephen-king-api.onrender.com/api/villain/11'},
    {'name': 'Arnie Cunningham',
     'url': 'https://stephen-king-api.onrender.com/api/villain/20'}]},
  {'id': 14,
   'Year': 1983,
   'Title': 'Pet Sematary',
   'handle': 'pet-sematary',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-18244-7',
   'Pages': 374,
   'Notes': ['Nominee, World Fantasy Award, 1984',
    'Runner-up (7th place), Locus Award for Best Fantasy Novel, 1984[2]'],
   'created_at': '2023-11-13T23:48:49.637Z',
   'villains': [{'name': 'Winston Church',
     'url': 'https://stephen-king-api.onrender.com/api/villain/13'},
    {'name': 'Gage Creed',
     'url': 'https://stephen-king-api.onrender.com/api/villain/15'},
    {'name': 'Victor Pascow',
     'url': 'https://stephen-king-api.onrender.com/api/villain/83'},
    {'name': 'Wendigo',
     'url': 'https://stephen-king-api.onrender.com/api/villain/110'}]},
  {'id': 15,
   'Year': 1983,
   'Title': 'Cycle of the Werewolf',
   'handle': 'cycle-of-the-werewolf',
   'Publisher': 'Land of Enchantment',
   'ISBN': '978-0-960-38282-8',
   'Pages': 127,
   'Notes': ['Illustrated by Bernie Wrightson'],
   'created_at': '2023-11-13T23:48:49.757Z',
   'villains': [{'name': 'Lester Lowe',
     'url': 'https://stephen-king-api.onrender.com/api/villain/68'}]},
  {'id': 16,
   'Year': 1984,
   'Title': 'The Talisman',
   'handle': 'the-talisman',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-69199-9',
   'Pages': 646,
   'Notes': ['Written with Peter Straub',
    'Nominee, World Fantasy Award, 1985',
    'Runner-up (4th place), Locus Award for Best Fantasy Novel, 1985[2]'],
   'created_at': '2023-11-13T23:48:49.872Z',
   'villains': []},
  {'id': 17,
   'Year': 1984,
   'Title': 'The Eyes of the Dragon',
   'handle': 'the-eyes-of-the-dragon',
   'Publisher': 'Philtrum Press (1984)Viking (1987)',
   'ISBN': '978-0-670-81458-9',
   'Pages': 326,
   'Notes': ['First published as a limited edition in 1984, then for the mass market in 1987'],
   'created_at': '2023-11-13T23:48:49.988Z',
   'villains': [{'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'}]},
  {'id': 18,
   'Year': 1984,
   'Title': 'Thinner',
   'handle': 'thinner',
   'Publisher': 'NAL',
   'ISBN': '978-0-453-00468-8',
   'Pages': 309,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:50.102Z',
   'villains': []},
  {'id': 19,
   'Year': 1986,
   'Title': 'It',
   'handle': 'it',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-81302-5',
   'Pages': 1138,
   'Notes': ['Winner, British Fantasy Award’s August Derleth Award, 1987',
    'Nominee, World Fantasy Award, 1987',
    'Runner-up (3rd place), Locus Award for Best Fantasy Novel, 1987[2]'],
   'created_at': '2023-11-13T23:48:50.223Z',
   'villains': [{'name': 'Henry Bowers',
     'url': 'https://stephen-king-api.onrender.com/api/villain/7'},
    {'name': 'Butch Bowers',
     'url': 'https://stephen-king-api.onrender.com/api/villain/8'},
    {'name': 'Greta Bowie',
     'url': 'https://stephen-king-api.onrender.com/api/villain/9'},
    {'name': 'Victor Criss',
     'url': 'https://stephen-king-api.onrender.com/api/villain/18'},
    {'name': 'Marcia Fadden',
     'url': 'https://stephen-king-api.onrender.com/api/villain/35'},
    {'name': 'John Garton',
     'url': 'https://stephen-king-api.onrender.com/api/villain/39'},
    {'name': 'Peter Gordon',
     'url': 'https://stephen-king-api.onrender.com/api/villain/43'},
    {'name': 'Patrick Hockstetter',
     'url': 'https://stephen-king-api.onrender.com/api/villain/53'},
    {'name': 'Belch Huggins',
     'url': 'https://stephen-king-api.onrender.com/api/villain/55'},
    {'name': 'It (Creature)',
     'url': 'https://stephen-king-api.onrender.com/api/villain/57'},
    {'name': 'Richard P. Macklin',
     'url': 'https://stephen-king-api.onrender.com/api/villain/69'},
    {'name': 'Alvin Marsh',
     'url': 'https://stephen-king-api.onrender.com/api/villain/72'},
    {'name': 'Sally Mueller',
     'url': 'https://stephen-king-api.onrender.com/api/villain/79'},
    {'name': 'Tom Rogan',
     'url': 'https://stephen-king-api.onrender.com/api/villain/91'},
    {'name': 'Christopher Unwin',
     'url': 'https://stephen-king-api.onrender.com/api/villain/107'}]},
  {'id': 20,
   'Year': 1987,
   'Title': 'The Dark Tower II: The Drawing of the Three',
   'handle': 'the-dark-tower-ii-the-drawing-of-the-three',
   'Publisher': 'Grant',
   'ISBN': '978-0-937986-90-5',
   'Pages': 400,
   'Notes': ['Runner-up (16th place), Locus Award for Best Fantasy Novel, 1988[2]'],
   'created_at': '2023-11-13T23:48:50.339Z',
   'villains': [{'name': 'Jack Mort',
     'url': 'https://stephen-king-api.onrender.com/api/villain/76'}]},
  {'id': 21,
   'Year': 1987,
   'Title': 'Misery',
   'handle': 'misery',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-81364-3',
   'Pages': 310,
   'Notes': ['Winner, Bram Stoker Award, 1988',
    'Nominee, World Fantasy Award, 1988[2]'],
   'created_at': '2023-11-13T23:48:50.459Z',
   'villains': [{'name': 'Annie Wilkes',
     'url': 'https://stephen-king-api.onrender.com/api/villain/114'}]},
  {'id': 22,
   'Year': 1987,
   'Title': 'The Tommyknockers',
   'handle': 'the-tommyknockers',
   'Publisher': 'Putnam',
   'ISBN': '978-0-399-13314-5',
   'Pages': 558,
   'Notes': ['Runner-up (16th place), Locus Award for Best Science Fiction Novel, 1988[2]'],
   'created_at': '2023-11-13T23:48:50.579Z',
   'villains': [{'name': 'Tommyknockers',
     'url': 'https://stephen-king-api.onrender.com/api/villain/104'}]},
  {'id': 23,
   'Year': 1989,
   'Title': 'The Dark Half',
   'handle': 'the-dark-half',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-82982-8',
   'Pages': 431,
   'Notes': ['Runner-up (2nd place), Locus Award for Best Horror Novel, 1990[2]'],
   'created_at': '2023-11-13T23:48:50.696Z',
   'villains': [{'name': 'George Stark',
     'url': 'https://stephen-king-api.onrender.com/api/villain/96'}]},
  {'id': 24,
   'Year': 1990,
   'Title': 'The Stand Uncut',
   'handle': 'the-stand-uncut',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-19957-5',
   'Pages': 1152,
   'Notes': ['The Complete & Uncut Edition',
    "Runner-up (2nd place), Locus Award's Best Horror/Dark Fantasy Novel, 1991[2]"],
   'created_at': '2023-11-13T23:48:50.809Z',
   'villains': []},
  {'id': 25,
   'Year': 1991,
   'Title': 'The Dark Tower III: The Waste Lands',
   'handle': 'the-dark-tower-iii-the-waste-lands',
   'Publisher': 'Grant',
   'ISBN': '978-0-937986-17-2',
   'Pages': 512,
   'Notes': ['Nominee, Bram Stoker Award, 1992',
    'Runner-up (3rd place), Locus Award for Best Horror/Dark Fantasy Novel, 1992[2]'],
   'created_at': '2023-11-13T23:48:50.926Z',
   'villains': [{'name': 'Blaine the Mono',
     'url': 'https://stephen-king-api.onrender.com/api/villain/3'},
    {'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'}]},
  {'id': 26,
   'Year': 1991,
   'Title': 'Needful Things',
   'handle': 'needful-things',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-83953-7',
   'Pages': 690,
   'Notes': ['Nominee, Bram Stoker Award, 1992',
    'Runner-up (13th place), Locus Award for Best Horror/Dark Fantasy Novel, 1992[2]'],
   'created_at': '2023-11-13T23:48:51.044Z',
   'villains': [{'name': 'Leland Gaunt',
     'url': 'https://stephen-king-api.onrender.com/api/villain/40'}]},
  {'id': 27,
   'Year': 1992,
   'Title': "Gerald's Game",
   'handle': 'gerald-s-game',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-84650-4',
   'Pages': 352,
   'Notes': [],
   'created_at': '2023-11-13T23:48:51.165Z',
   'villains': [{'name': 'Gerald Burlingame',
     'url': 'https://stephen-king-api.onrender.com/api/villain/41'},
    {'name': 'Raymond Andrew Joubert',
     'url': 'https://stephen-king-api.onrender.com/api/villain/61'},
    {'name': 'Tom Mahout',
     'url': 'https://stephen-king-api.onrender.com/api/villain/103'}]},
  {'id': 28,
   'Year': 1992,
   'Title': 'Dolores Claiborne',
   'handle': 'dolores-claiborne',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-84452-4',
   'Pages': 305,
   'Notes': ['Runner-up (14th place), Locus Award for Best Horror/Dark Fantasy Novel, 1993[2]'],
   'created_at': '2023-11-13T23:48:51.295Z',
   'villains': [{'name': 'Joe St. George',
     'url': 'https://stephen-king-api.onrender.com/api/villain/95'}]},
  {'id': 29,
   'Year': 1994,
   'Title': 'Insomnia',
   'handle': 'insomnia',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-85503-2',
   'Pages': 787,
   'Notes': ['Nominee, Bram Stoker Award, 1995',
    'Runner-up (3rd place), Locus Award for Best Fantasy/Horror Novel, 1995[2]'],
   'created_at': '2023-11-13T23:48:51.415Z',
   'villains': [{'name': 'Crimson King',
     'url': 'https://stephen-king-api.onrender.com/api/villain/17'},
    {'name': 'Susan Day',
     'url': 'https://stephen-king-api.onrender.com/api/villain/23'}]},
  {'id': 30,
   'Year': 1995,
   'Title': 'Rose Madder',
   'handle': 'rose-madder',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-85869-9',
   'Pages': 420,
   'Notes': ['Runner-up (3rd place), Locus Award for Best Horror/Dark Fantasy Novel, 1995[2]'],
   'created_at': '2023-11-13T23:48:51.533Z',
   'villains': [{'name': 'Norman Daniels',
     'url': 'https://stephen-king-api.onrender.com/api/villain/22'},
    {'name': 'Susan Day',
     'url': 'https://stephen-king-api.onrender.com/api/villain/23'}]},
  {'id': 31,
   'Year': 1996,
   'Title': 'The Green Mile',
   'handle': 'the-green-mile',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-19049-9978-0-451-19052-9978-0-451-19054-3978-0-451-19055-0978-0-451-19056-7978-0-451-19057-4',
   'Pages': 400,
   'Notes': ['Winner, Bram Stoker Award, 1997',
    'Runner-up (8th place), Locus Award for Best Horror/Dark Fantasy Novel, 1997[2]'],
   'created_at': '2023-11-13T23:48:51.660Z',
   'villains': [{'name': 'Percy Wetmore',
     'url': 'https://stephen-king-api.onrender.com/api/villain/111'},
    {'name': 'William Wharton',
     'url': 'https://stephen-king-api.onrender.com/api/villain/112'}]},
  {'id': 32,
   'Year': 1996,
   'Title': 'Desperation',
   'handle': 'desperation',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-86836-0',
   'Pages': 704,
   'Notes': ['Twin novel of The Regulators',
    'Winner, Locus Award for Best Horror/Dark Fantasy Novel, 1997[2]'],
   'created_at': '2023-11-13T23:48:51.784Z',
   'villains': []},
  {'id': 33,
   'Year': 1996,
   'Title': 'The Regulators',
   'handle': 'the-regulators',
   'Publisher': 'Dutton',
   'ISBN': '978-0-525-94190-3',
   'Pages': 480,
   'Notes': ['Published under pseudonym Richard Bachman',
    'Twin novel of Desperation'],
   'created_at': '2023-11-13T23:48:51.900Z',
   'villains': []},
  {'id': 34,
   'Year': 1997,
   'Title': 'The Dark Tower IV: Wizard and Glass',
   'handle': 'the-dark-tower-iv-wizard-and-glass',
   'Publisher': 'Grant',
   'ISBN': '978-1-880418-38-3',
   'Pages': 787,
   'Notes': ['Runner-up (4th place), Locus Award for Best Fantasy Novel, 1998',
    'Runner-up (6th place), Locus Award for Best Art Book, 1998[2]'],
   'created_at': '2023-11-13T23:48:52.019Z',
   'villains': [{'name': 'Blaine the Mono',
     'url': 'https://stephen-king-api.onrender.com/api/villain/3'},
    {'name': 'Cordelia Delgado',
     'url': 'https://stephen-king-api.onrender.com/api/villain/24'},
    {'name': 'Rhea Dubativo',
     'url': 'https://stephen-king-api.onrender.com/api/villain/32'},

In [34]:
import requests
import pandas as pd
url="https://dogapi.dog/api-docs/v2/swagger.json"
res=requests.get(url)
jsonData=res.json()

In [35]:
jsonData

{'openapi': '3.0.1',
 'info': {'title': 'API V2',
  'version': '1.0.0',
  'description': 'The Dog API provides a wealth of information on dog breeds, groups, and fun facts. Access and integrate this data into your website or application with our easy-to-use JSON API.',
  'termsOfService': 'https://dogapi.dog/terms',
  'contact': {'email': 'dev@dogapi.dog'},
  'license': {'name': 'MIT',
   'url': 'https://github.com/kinduff/dogapi.dog/blob/master/LICENSE'}},
 'servers': [{'url': 'https://dogapi.dog/api/v2'}],
 'paths': {'/breeds': {'get': {'summary': 'list breeds',
    'tags': ['Breeds'],
    'parameters': [{'name': 'page[number]',
      'in': 'query',
      'required': False,
      'schema': {'type': 'integer', 'minimum': 1},
      'description': 'Page number for pagination'},
     {'name': 'page[size]',
      'in': 'query',
      'required': False,
      'schema': {'type': 'integer', 'minimum': 1, 'maximum': 1000},
      'description': 'Number of records per page (max 1000)'}],
    'responses': {'200': {'description': 'successful',
      'content': {'application/json': {'examples': {'example': {'value': {'data': [{'id': 'f9643a80-af1d-422a-9f15-18d466822053',
             'type': 'breed',
             'attributes': {'name': 'Caucasian Shepherd Dog',
              'description': 'The Caucasian Shepherd dog is a serious guardian breed and should never be taken lightly.',
              'hypoallergenic': False,
              'life': {'min': 15, 'max': 20},
              'male_weight': {'min': 50, 'max': 100},
              'female_weight': {'min': 50, 'max': 100}}},
            {'id': 'dc5e84f8-9151-4624-836c-25b4e313118b',
             'type': 'breed',
             'attributes': {'name': 'Bouvier des Flandres',
              'description': "They don't build 'em like this anymore.",
              'hypoallergenic': False,
              'life': {'min': 10, 'max': 14},
              'male_weight': {'min': 30, 'max': 40},
              'female_weight': {'min': 25, 'max': 35}}}],
           'meta': {'pagination': {'current': 1, 'records': 9}},
           'links': {'self': 'https://dogapi.dog/api/v2/breeds',
            'current': 'https://dogapi.dog/api/v2/breeds?page[number]=1',
            'next': 'https://dogapi.dog/api/v2/breeds?page[number]=2',
            'last': 'https://dogapi.dog/api/v2/breeds?page[number]=2'}}}}}}}}}},
  '/breeds/{id}': {'get': {'summary': 'get breed with non-existing id',
    'tags': ['Breeds'],
    'parameters': [{'name': 'id',
      'in': 'path',
      'required': True,
      'schema': {'type': 'string'}}],
    'responses': {'200': {'description': 'successful',
      'content': {'application/json': {'examples': {'example': {'value': {'data': {'id': 'f9643a80-af1d-422a-9f15-18d466822053',
            'type': 'breed',
            'attributes': {'name': 'Caucasian Shepherd Dog',
             'life': {'min': 15, 'max': 20},
             'male_weight': {'min': 50, 'max': 100},
             'female_weight': {'min': 50, 'max': 100},
             'description': 'The Caucasian Shepherd dog is a serious guardian breed and should never be taken lightly.',
             'hypoallergenic': False}},
           'links': {'self': 'https://dogapi.dog/api/v2/breeds/f9643a80-af1d-422a-9f15-18d466822053'}}}}}}},
     '404': {'description': 'not-found'}}}},
  '/facts': {'get': {'summary': 'list facts',
    'tags': ['Facts'],
    'parameters': [{'name': 'limit',
      'in': 'query',
      'required': False,
      'schema': {'type': 'integer', 'minimum': 1, 'maximum': 5, 'default': 1},
      'description': 'Number of facts to return (max 5, defaults to 1)'}],
    'responses': {'200': {'description': 'successful',
      'content': {'application/json': {'examples': {'example': {'value': {'data': [{'id': '1cd1a16d-6fe1-40ea-9dd2-c21dd0f7c24e',
             'type': 'fact',
             'attributes': {'body': 'Many foot disorders in dogs are caused by long toenails.'}}]}}}}}}}}},
  '/groups': {'get': {'summary': 'list groups',
    'tags': ['Groups'],
    'parameters': [{'name': 'page[number]',
      'in': 'query',
      'required': False,
      'schema': {'type': 'integer', 'minimum': 1},
      'description': 'Page number for pagination'},
     {'name': 'page[size]',
      'in': 'query',
      'required': False,
      'schema': {'type': 'integer', 'minimum': 1, 'maximum': 1000},
      'description': 'Number of records per page (max 1000)'}],
    'responses': {'200': {'description': 'successful',
      'content': {'application/json': {'examples': {'example': {'value': {'data': [{'id': '02124eb6-1baa-410c-90ea-6b8629fb0837',
             'type': 'group',
             'attributes': {'name': 'Foundation Stock Service'},
             'relationships': {'breeds': {'data': [{'id': 'b0b6810c-fb88-4987-ad0a-ae0440b04634',
                 'type': 'breed'},
                {'id': '38e06144-2ac3-43c0-981c-f8598eabc902',
                 'type': 'breed'}]}}},
            {'id': '256db247-70ce-4f08-b6a6-60b27ce369d1',
             'type': 'group',
             'attributes': {'name': 'Herding Group'},
             'relationships': {'breeds': {'data': [{'id': '85d5a702-057f-42e3-a24c-b56e0aa94bf9',
                 'type': 'breed'},
                {'id': 'eef99f80-266a-4659-a1e7-3af639010984',
                 'type': 'breed'}]}}}],
           'links': {'self': 'https://dogapi.dog/api/v2/groups',
            'current': 'https://dogapi.dog/api/v2/groups?page[number]=1',
            'next': 'https://dogapi.dog/api/v2/groups?page[number]=2',
            'last': 'https://dogapi.dog/api/v2/groups?page[number]=2'}}}}}}}}}},
  '/groups/{id}': {'get': {'summary': 'get group with non-existing id',
    'tags': ['Groups'],
    'parameters': [{'name': 'id',
      'in': 'path',
      'required': True,
      'schema': {'type': 'string'}}],
    'responses': {'200': {'description': 'successful',
      'content': {'application/json': {'examples': {'example': {'value': {'data': {'id': '02124eb6-1baa-410c-90ea-6b8629fb0837',
            'type': 'group',
            'attributes': {'name': 'Foundation Stock Service'},
            'relationships': {'breeds': {'data': [{'id': 'b0b6810c-fb88-4987-ad0a-ae0440b04634',
                'type': 'breed'},
               {'id': '4bc90a09-5406-4739-96c6-ac2161fbfa4e',
                'type': 'breed'}]}}},
           'links': {'self': 'https://dogapi.dog/api/v2/groups/02124eb6-1baa-410c-90ea-6b8629fb0837'}}}}}}},
     '404': {'description': 'not-found'}}}}}}

In [44]:
import pandas as pd
df=pd.json_normalize(jsonData)
df

,openapi,servers,info.title,info.version,info.description,info.termsOfService,info.contact.email,info.license.name,info.license.url,paths./breeds.get.summary,...,paths./groups/{id}.get.summary,paths./groups/{id}.get.tags,paths./groups/{id}.get.parameters,paths./groups/{id}.get.responses.200.description,paths./groups/{id}.get.responses.200.content.application/json.examples.example.value.data.id,paths./groups/{id}.get.responses.200.content.application/json.examples.example.value.data.type,paths./groups/{id}.get.responses.200.content.application/json.examples.example.value.data.attributes.name,paths./groups/{id}.get.responses.200.content.application/json.examples.example.value.data.relationships.breeds.data,paths./groups/{id}.get.responses.200.content.application/json.examples.example.value.links.self,paths./groups/{id}.get.responses.404.description
0,3.0.1,[{'url': 'https://dogapi.dog/api/v2'}],API V2,1.0.0,The Dog API provides a wealth of information o...,https://dogapi.dog/terms,dev@dogapi.dog,MIT,https://github.com/kinduff/dogapi.dog/blob/mas...,list breeds,...,get group with non-existing id,[Groups],"[{'name': 'id', 'in': 'path', 'required': True...",successful,02124eb6-1baa-410c-90ea-6b8629fb0837,group,Foundation Stock Service,[{'id': 'b0b6810c-fb88-4987-ad0a-ae0440b04634'...,https://dogapi.dog/api/v2/groups/02124eb6-1baa...,not-found

In [40]:
df=df[["openapi","servers","info.title","info.description"]]

In [41]:
df

,openapi,servers,info.title,info.description
0,3.0.1,[{'url': 'https://dogapi.dog/api/v2'}],API V2,The Dog API provides a wealth of information o...

# WEB SCRAPING

In [4]:
import requests
url="https://www.scrapethissite.com/pages/simple/"
resp=requests.get(url)

200

In [15]:
if resp.status_code==200:
    with open("scrape_data/s_data.html","w",encoding="utf-8") as f:
        f.write(resp.text)

# BEAUTIFULSOUP

In [16]:
pip install beautifulsoup4

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

Requirement already satisfied: beautifulsoup4 in c:\programdata\anaconda3\lib\site-packages (4.12.3)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)

In [19]:
from bs4 import BeautifulSoup

with open("scrape_data/s_data.html","r") as f:
    html_content=f.read()
soup=BeautifulSoup(html_content,"lxml")

In [42]:
soup.find("h1")
all_h3=soup.find_all("h3")

all_countries=[]

for h3 in all_h3:
    name=h3.get_text(strip=True)

    population=h3.find_next("div").select("span.country-population")[0].get_text(strip=True)
    print(h3.find_next("div").select_one("span.country-population").get_text(strip=True))

    # print(h3.attrs)
    
    all_countries.append([name,population])

84000
4975593
29121286
86754
13254
2986952
2968000
13068161
0
41343201
57881
8205000
21515754
71566
26711
8303512
4590000
285653
156118464
10403000
16241811
7148785
738004
9863117
9056010
8450
65365
395027
9947418
18012
201103330
301790
699847
0
2029307
9685000
314522
33679000
628
70916439
4844927
3039126
7581000
21058798
21388
16746491
19294149
1330044000
47790000
4516220
11423000
508659
141766
1500
1102677
10476000
81802257
740528
5484000
72813
9823821
34586184
14790608
1291170
80471869
273008
5792984
46505963
88013491
5244000
875983
2638
107708
48228
64768389
1545255
62348447
107818
4630000
195506
65228
24339838
27884
56375
1593256
10324025
443000
1014999
11000000
30
13550440
159358
1565126
748486
6898686
0
7989415
4491000
9648924
9982000
242968342
4622917
7353985
75049
1173108018
4000
29671605
76923300
308910
60340328
90812
2847232
6407085
127288000
40046566
5776500
14453680
92533
773407
51134
22912177
48422644
2789132
44270
15340000
6368162
4125247
160922
35000
21513990
3685076
1919552
2944459
497538
2217969
6461454
31627428
32965
4324000
666730
35925
21281844
65859
2062294
13796354
53414374
3086918
449198
53883
432900
3205060
9341
403000
1294104
395650
15447500
112468855
28274729
22061451
2128471
216494
15878271
1828
154000000
5995928
16645000
5009150
28951852
10065
2166
4252277
2967717
3410676
29907003
270485
6064515
99900177
184404791
38500000
7012
46
3916632
3800000
10676000
19907
6375830
840926
776948
21959278
7344847
140702000
11055976
25731776
559198
88340
35000000
9828655
4701069
7460
2007000
2550
5455000
5245695
31477
12323252
10112453
492829
8260490
175808
6052064
37429
22198110
1354051
20556
10543464
140
6587239
67089500
7487489
1466
1154625
4940916
10589025
122580
77804122
1228691
10472
22894384
41892895
45415596
33398682
0
310232863
3477000
27865738
921
104217
27223228
21730
108708
89571130
221552
16025
192001
1800000
23495361
159042
49000000
13460305
11651858

In [46]:
import pandas as pd
df=pd.DataFrame(all_countries,columns=["name","population"])

In [47]:
df

                     name population
0                 Andorra      84000
1    United Arab Emirates    4975593
2             Afghanistan   29121286
3     Antigua and Barbuda      86754
4                Anguilla      13254
..                    ...        ...
245                 Yemen   23495361
246               Mayotte     159042
247          South Africa   49000000
248                Zambia   13460305
249              Zimbabwe   11651858

[250 rows x 2 columns]

In [48]:
df.to_csv("cleaned_data/data.csv",index=False)

# ASSIGNMENT 1

In [2]:
import requests
from bs4 import BeautifulSoup
page_count=1
while True:
    url=f"https://quotes.toscrape.com/page/{page_count}/"
    resp=requests.get(url)
    soup=BeautifulSoup(resp.text,"lxml")
    quotes=soup.select("div.quotes")
    if not quotes:
        print("no valid pages anymore")
        break;
    with open(f"scrape_data/q_data{page_count}.html","w",encoding="utf-8") as f:
        f.write(resp.text)
    print(f"downloaded data from page{page_count}")
    page_count=page_count+1

ConnectionError: HTTPSConnectionPool(host='quotes.toscrape.com', port=443): Max retries exceeded with url: /page/1/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000026A9D13D7F0>: Failed to resolve 'quotes.toscrape.com' ([Errno 11001] getaddrinfo failed)"))

In [14]:
with open("scrape_data/s_data.html","r") as f:
    html_content=f.read()

soup2=BeautifulSoup(html_content,"lxml")

soup2.find("span")